---
- name: Start jellyfin
  block:
    - name: Create Jellyfin Directories
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
      with_items:
        - '{{ jellyfin_config_directory }}'
- name: Permission share data
  file:
    path: '{{ item }}'
    owner: '{{ jellyfin_user_id }}'
    group: '{{ jellyfin_group_id }}'
    mode: u=rwX,g=rwX,o=rX
    recurse: true
  loop:
    # Migrating from host install back to Docker
    - /etc/jellyfin:/etc/jellyfin
    - /var/cache/jellyfin:/var/cache/jellyfin
    - /var/lib/jellyfin:/var/lib/jellyfin
    - /var/log/jellyfin:/var/log/jellyfin
    - '{{ jellyfin_config_directory }}'
- name: Jellyfin Docker Container
  docker_container:
    name: jellyfin
    image: linuxserver/jellyfin
    pull: true
    volumes:
      - '{{ jellyfin_config_directory }}:/config:rw'
      - '{{ jellyfin_movies_directory }}:/movies:{{ jellyfin_movies_permissions
        }}'
      - '{{ jellyfin_music_directory }}:/music:{{ jellyfin_music_permissions }}'
      - '{{ jellyfin_photos_directory }}:/photos:{{ jellyfin_photos_permissions
        }}'
      - '{{ jellyfin_tv_directory }}:/tv:{{ jellyfin_tv_permissions }}'
      - '{{ jellyfin_books_directory }}:/books:{{ jellyfin_books_permissions }}'
      - '{{ jellyfin_audiobooks_directory }}:/audiobooks:{{ jellyfin_audiobooks_permissions
        }}'
      - '{{ youtubedlmaterial_downloads_directory }}:/youtube:ro'
      - '{{ jellyfin_migrate_from_bare_metal_directory }}/etc:/etc/jellyfin:rw'
      - '{{ jellyfin_migrate_from_bare_metal_directory }}/var/lib/jellyfin:/var/lib/jellyfin:rw'
      - '{{ jellyfin_migrate_from_bare_metal_directory }}/var/log/jellyfin:/var/log/jellyfin:rw'
      - '{{ jellyfin_migrate_from_bare_metal_directory }}/var/cache/jellyfin:/var/cache/jellyfin:rw'
    ports:
      - '{{ jellyfin_port_http }}:8096'
      - '{{ jellyfin_port_https }}:8920'
      # Make it discoverable
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      # NOTE: had to change to card1 after a weird reboot
      - /dev/dri/card1:/dev/dri/card0
    env:
      TZ: '{{ ansible_nas_timezone }}'
      PUID: '{{ jellyfin_user_id }}'
      PGID: '{{ jellyfin_group_id }}'
      DOCKER_MODS: linuxserver/mods:jellyfin-amd
    restart_policy: unless-stopped
    memory: '{{ jellyfin_memory }}'
    labels:
      traefik.enable: '{{ jellyfin_available_externally | string }}'
      traefik.http.routers.jellyfin.rule: Host(`{{ jellyfin_hostname }}.{{ ansible_nas_domain
        }}`)
      traefik.http.routers.jellyfin.tls.certresolver: letsencrypt
      traefik.http.routers.jellyfin.tls.domains[0].main: '{{ ansible_nas_domain }}'
      traefik.http.routers.jellyfin.tls.domains[0].sans: '*.{{ ansible_nas_domain }}'
      traefik.http.services.jellyfin.loadbalancer.server.port: '8096'
