---
- hosts: jellyfin


  roles:

    ###
    ### Requirements
    ###

    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint


    ###
    ### Ansible-NAS Roles
    ###
    - role: ansible-nas-general
      tags:
        - ansible-nas-general
        - ansible-nas

    - role: ansible-nas-docker
      tags:
        - ansible-nas-docker
        - ansible-nas


    ###
    ### Applications
    ###
    - role: airsonic
      tags:
        - airsonic
      when: (airsonic_enabled | default(False))

    - role: bazarr
      tags:
        - bazarr
      when: (bazarr_enabled | default(False))

    - role: booksonic
      tags:
        - booksonic
      when: (booksonic_enabled | default(False))

    - role: couchpotato
      tags:
        - couchpotato
      when: (couchpotato_enabled | default(False))

    - role: deluge
      tags:
        - deluge
      when: (deluge_enabled | default(False))

    - role: emby
      tags:
        - emby
      when: (emby_enabled | default(False))

    - role: glances
      tags:
        - glances
      when: (glances_enabled | default(False))

    - role: gotify
      tags:
        - gotify
      when: (gotify_enabled | default(False))

    - role: lidarr
      tags:
        - lidarr
      when: (lidarr_enabled | default(False))

    - role: netdata
      tags:
        - netdata
      when: (netdata_enabled | default(False))

    - role: nzbget
      tags:
        - nzbget
      when: (nzbget_enabled | default(False))

    - role: organizr
      tags:
        - organizr
      when: (organizr_enabled | default(False))

    - role: portainer
      tags:
        - portainer
      when: (portainer_enabled | default(False))

    - role: prowlarr
      tags:
        - prowlarr
      when: (prowlarr_enabled | default(False))

    - role: ombi
      tags:
        - ombi
      when: (ombi_enabled | default(False))

    - role: readarr
      tags:
        - readarr
      when: (readarr_enabled | default(False))

    - role: radarr
      tags:
        - radarr
      when: (radarr_enabled | default(False))

    - role: sickchill
      tags:
        - sickchill
      when: (sickchill_enabled | default(False))

    - role: sonarr
      tags:
        - sonarr
      when: (sonarr_enabled | default(False))

    - role: syncthing
      tags:
        - syncthing
      when: (syncthing_enabled | default(False))

    - role: watchtower
      tags:
        - watchtower
      when: (watchtower_enabled | default(False))

  tasks:
    - import_tasks: tasks/thelounge.yml
      when: (thelounge_enabled | default(False))
      tags: thelounge

    - import_tasks: tasks/calibre.yml
      when: (calibre_enabled | default(False))
      tags: calibre

    - import_tasks: tasks/jellyfin.yml
      when: (jellyfin_enabled | default(False))
      tags: jellyfin

    - import_tasks: tasks/ubooquity.yml
      when: (ubooquity_enabled | default(False))
      tags: ubooquity

