---
- hosts: sandbox

  roles:

    ###
    ### Requirements
    ###

    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint


    ###
    ### Ansible-NAS Roles
    ###
    - role: ansible-nas-general
      tags:
        - ansible-nas-general
        - ansible-nas

    - role: ansible-nas-docker
      tags:
        - ansible-nas-docker
        - ansible-nas


    ###
    ### Applications
    ###
    - role: couchpotato
      tags:
        - couchpotato
      when: (couchpotato_enabled | default(False))

    - role: deluge
      tags:
        - deluge
      when: (deluge_enabled | default(False))

    - role: duplicati
      tags:
        - duplicati
      when: (duplicati_enabled | default(False))
    - role: gitea
      tags:
        - gitea
      when: (gitea_enabled | default(False))

    - role: gitlab
      tags:
        - gitlab
      when: (gitlab_enabled | default(False))

    - role: glances
      tags:
        - glances
      when: (glances_enabled | default(False))

    - role: heimdall
      tags:
        - heimdall
      when: (heimdall_enabled | default(False))

    - role: homeassistant
      tags:
        - homeassistant
      when: (homeassistant_enabled | default(False))

    - role: jackett
      tags:
        - jackett
      when: (jackett_enabled | default(False))

    - role: lidarr
      tags:
        - lidarr
      when: (lidarr_enabled | default(False))

    - role: netdata
      tags:
        - netdata
      when: (netdata_enabled | default(False))

    - role: nextcloud
      tags:
        - nextcloud
      when: (nextcloud_enabled | default(False))

    - role: nzbget
      tags:
        - nzbget
      when: (nzbget_enabled | default(False))

    - role: portainer
      tags:
        - portainer
      when: (portainer_enabled | default(False))

    - role: radarr
      tags:
        - radarr
      when: (radarr_enabled | default(False))

    - role: radarr
      tags:
        - radarr
      when: (radarr_enabled | default(False))

    - role: sickchill
      tags:
        - sickchill
      when: (sickchill_enabled | default(False))

    - role: sonarr
      tags:
        - sonarr
      when: (sonarr_enabled | default(False))

    - role: transmission
      tags:
        - transmission
      when: (transmission_enabled | default(False))
      
    - role: transmission-with-openvpn
      tags:
        - transmission_openvpn
      when: (transmission_openvpn_enabled | default(False))

    - role: utorrent
      tags:
        - utorrent
      when: (utorrent_enabled | default(False))

    - role: traefik
      tags:
        - traefik
      when: (traefik_enabled | default(False))

    - role: watchtower
      tags:
        - watchtower
      when: (watchtower_enabled | default(False))

    - role: dokuwiki
      tags:
        - dokuwiki
      when: (dokuwiki_enabled | default(False))

  tasks:
    - import_tasks: tasks/thelounge.yml
      when: (thelounge_enabled | default(False))
      tags: thelounge

    - import_tasks: tasks/timemachine.yml
      when: (timemachine_enabled | default(False))
      tags: timemachine

    - import_tasks: tasks/stats.yml
      when: (stats_enabled | default(False))
      tags: stats

    - import_tasks: tasks/guacamole.yml
      when: (guacamole_enabled | default(False))
      tags: guacamole

    - import_tasks: tasks/joomla.yml
      when: (joomla_enabled | default(False))
      tags: joomla

    - import_tasks: tasks/wallabag.yml
      when: (wallabag_enabled | default(False))
      tags: wallabag

    - import_tasks: tasks/mosquitto.yml
      when: (mosquitto_enabled | default(False))
      tags: mosquitto

    - import_tasks: tasks/calibre.yml
      when: (calibre_enabled | default(False))
      tags: calibre

    - import_tasks: tasks/openhab.yml
      when: (openhab_enabled | default(False))
      tags: openhab

    - import_tasks: tasks/jellyfin.yml
      when: (jellyfin_enabled | default(False))
      tags: jellyfin

    - import_tasks: tasks/krusader.yml
      when: (krusader_enabled | default(False))
      tags: krusader

    - import_tasks: tasks/ubooquity.yml
      when: (ubooquity_enabled | default(False))
      tags: ubooquity

    - import_tasks: tasks/youtubedlmaterial.yml
      when: (youtubedlmaterial_enabled | default(False))
      tags: youtubedlmaterial

    - import_tasks: tasks/virtual_desktop.yml
      when: (virtual_desktop_enabled | default(False))
      tags: virtual_desktop

    - import_tasks: tasks/pytivo.yml
      when: (pytivo_enabled | default(False))
      tags: pytivo
