---
- name: Create ansible-nas group
  group:
    name: {{ ansible_nas_user }}
    state: present

- name: Create ansible-nas user
  user:
    name: {{ ansible_nas_user }}
    state: present
    system: yes
    update_password: on_create
    create_home: yes
    group: {{ ansible_nas_user }}
    shell: /usr/sbin/nologin
