---
- name: Create ansible-nas group
  ansible.builtin.group:
    name: ansible-nas
    state: present

- name: Create ansible-nas user
  ansible.builtin.user:
    name: ansible-nas
    # uid/gid set to match existing perms before hogwarts -> ghost
    uid: 997
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: ansible-nas
    shell: /usr/sbin/nologin

- name: Add www-data user to ansible-nas group for Nextcloud purposes
  user:
    name: www-data
    append: true
    state: present
    groups:
      - ansible-nas
