---
- name: Create paperless_ngx directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ paperless_ngx_config_directory }}"
    - "{{ paperless_ngx_files_directory }}"
    - "{{ paperless_ngx_postgres_directory }}"
    - "{{ paperless_ngx_data_directory }}"
    - "{{ paperless_ngx_export_directory }}"
    - "{{ paperless_ngx_media_directory }}"
    - "{{ paperless_ngx_consume_directory }}"


- name: Create paperless_ngx network
  docker_network:
    name: "{{ paperless_ngx_container_network_name }}"

- name: paperless_ngx redis broker
  docker_container:
    name: "{{ paperless_ngx_container_name_redis }}"
    image: redis:6.0
    pull: true
    restart_policy: unless-stopped
    memory: "{{ paperless_ngx_redis_memory }}"
    networks:
      - name: "{{ paperless_ngx_container_network_name }}"

- name: paperless_ngx postgres Docker Container
  docker_container:
    name: "{{ paperless_ngx_container_name_postgres }}"
    image: postgres:13
    pull: true
    volumes:
      - "{{ paperless_ngx_postgres_directory }}:/var/lib/postgresql/data"
    env:
      POSTGRES_DB: "{{ paperless_ngx_postgres_db }}"
      POSTGRES_USER: "{{ paperless_ngx_postgres_user }}"
      POSTGRES_PASSWORD: "{{ paperless_ngx_postgres_password }}"
    restart_policy: unless-stopped
    memory: "{{ paperless_ngx_postgres_memory }}"
    networks:
      - name: "{{ paperless_ngx_container_network_name }}"

- name: paperless_ngx UI Docker Container
  docker_container:
    name: "{{ paperless_ngx_container_name_uiserver }}"
    # image: jonaswinkler/paperless-ng:latest
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    pull: true
    volumes:
      - "{{ paperless_ngx_data_directory }}:/usr/src/paperless/data"
      - "{{ paperless_ngx_media_directory }}:/usr/src/paperless/media"
      - "{{ paperless_ngx_export_directory }}:/usr/src/paperless/export"
      - "{{ paperless_ngx_consume_directory }}:/usr/src/paperless/consume"
    ports:
      - "{{ paperless_ngx_port }}:8000"
    env:
      PAPERLESS_REDIS: "redis://{{ paperless_ngx_container_name_redis | string }}:6379"
      PAPERLESS_DBHOST: "{{ paperless_ngx_container_name_postgres | string }}"
      USERMAP_UID: "{{ paperless_ngx_user_id }}"
      USERMAP_GID: "{{ paperless_ngx_group_id }}"
      PAPERLESS_OCR_LANGUAGES: "{{ paperless_ngx_languages }}"
    restart_policy: unless-stopped
    memory: "{{ paperless_ngx_ui_memory }}"
    networks:
      - name: "{{ paperless_ngx_container_network_name }}"
