http:
 #region routers 
  routers:
    # proxmox:
    #   entryPoints:
    #     - "https"
    #   rule: "Host(`proxmox.paynepride.com`)"
    #   middlewares:
    #     - default-headers
    #   tls: 
    #     certResolver: letsencrypt
    #   service: proxmox
    jellyfin_local:
    jellyfin2:
      entryPoints:
        - "websecure"
      rule: "Host(`jellyfin2.paynepride.com`)"
      middlewares:
        - https-redirect
        - default-headers
        # - extended-whitelist
      tls: 
        certResolver: letsencrypt
      service: jellyfin
    jellyfin:
      entryPoints:
        - "websecure"
      rule: "Host(`jellyfin.paynepride.com`)"
      middlewares:
        - https-redirect
        - default-headers
        # - extended-whitelist
      tls: 
        certResolver: letsencrypt
      service: jellyfin
    pihole:
      entryPoints:
        - "websecure"
      rule: "Host(`pihole.paynepride.com`)"
      middlewares:
        # - default-headers
        - addprefix-pihole
        - default-whitelist
      tls: 
        certResolver: letsencrypt
      service: pihole
    # truenas:
    #   entryPoints:
    #     - "http"
    #   rule: "Host(`truenas.paynepride.com`)"
    #   middlewares:
    #     - default-headers
    #   # tls: {}
    #   service: truenas
    littlelink:  # website 
      entryPoints:
        - "websecure"
      rule: "Host(`littlelink.paynepride.com`)"
      tls:
        certResolver: letsencrypt
      service: littlelink
    # blog:  # website 
    #   entryPoints:
    #     - "websecure"
    #   rule: "Host(`blog.paynepride.com`)"
    #   tls:
    #     certResolver: letsencrypt
    #   service: blog
    smallgroup:  # tidler notes 
      entryPoints:
        - "websecure"
      rule: "Host(`smallgroup.paynepride.com`)"
      tls:
        certResolver: letsencrypt
      service: smallgroup
    piwigo:  # piwigo
      entryPoints:
        - "websecure"
      rule: "Host(`www.paynepride.com`)"
      tls:
        certResolver: letsencrypt
      service: piwigo

#endregion
#region services
  services:
    # proxmox:
    #   loadBalancer:
    #     servers:
    #       - url: "http://192.168.1.100:8006"
    #     passHostHeader: true
    jellyfin_local:
    jellyfin2:
    jellyfin:
      loadBalancer:
        servers:
          - url: "http://192.168.1.4:8096"
        passHostHeader: true
    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.1.3:80"
        passHostHeader: true
    # truenas:
    #   loadBalancer:
    #     servers:
    #       - url: "http://192.168.1.24"
    #     passHostHeader: true
    littlelink:
      loadBalancer:
        servers:
          - url: "http://192.168.1.7:8889"
        passHostHeader: true
    # blog:
    #   loadBalancer:
    #     servers:
    #       - url: "http://192.168.1.7:8091"
    #     passHostHeader: true
    smallgroup:
      loadBalancer:
        servers:
          - url: "http://192.168.1.7:8092"
        passHostHeader: true
    piwigo:
      loadBalancer:
        servers:
          - url: "http://192.168.1.124"
        passHostHeader: true
#endregion
  middlewares:
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"
    https-redirect:
      redirectScheme:
        scheme: https

    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.6.0.0/24"  # wg
        - "192.168.1.0/24"  # lan
        - "172.17.0.0/16"  # docker

    extended-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.6.0.0/24"  # wg
        - "192.168.1.0/24"  # lan
        - "172.17.0.0/16"  # docker
        - "71.66.253.233/32"  # block WAN

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers
