---
http:
  # region routers
  routers:
    ytdl:
      entryPoints:
        - websecure
      rule: Host(`ytdl.paynepride.com`)
      middlewares:
        - simple-auth
      tls:
        certResolver: letsencrypt
      service: ytdl
    stable-diffusion2:
      entryPoints:
        - websecure
      rule: Host(`stable-diffusion2.paynepride.com`)
      middlewares:
        - simple-auth
      tls:
        certResolver: letsencrypt
      service: stable_diffusion2
    onedev:
      entryPoints:
        - websecure
      rule: Host(`onedev.paynepride.com`)
      tls:
        certResolver: letsencrypt
      service: stable_diffusion2
    tabbyml:
      entryPoints:
        - websecure
      rule: Host(`tabbyml.paynepride.com`)
      tls:
        certResolver: letsencrypt
      service: tabbyml
      # middlewares:
      #   - default-headers
      #   - default-whitelist
    pihole:
      entryPoints:
        - websecure
      rule: Host(`pihole.paynepride.com`)
      middlewares:
        # - default-headers
        - addprefix-pihole
        - default-whitelist
      tls:
        certResolver: letsencrypt
      service: pihole
    uptime_kuma_summary:
      entryPoints:
        - websecure
      rule: Host(`status.paynepride.com`)
      tls:
        certResolver: letsencrypt
      service: uptime_kuma_summary
      middlewares:
        - redirect-uptime
    littlelink:  # website
      entryPoints:
        - websecure
      rule: Host(`littlelink.paynepride.com`)
      tls:
        certResolver: letsencrypt
      service: littlelink
    rickroll:  # rick roll
      entryPoints:
        - websecure
      rule: Host(`rr.paynepride.com`)
      tls:
        certResolver: letsencrypt
      service: rickroll
  # endregion
  # region services
  services:
    ytdl:
      loadBalancer:
        servers:
          - url: http://ghost:8001
        passHostHeader: true
    onedev:
      loadBalancer:
        servers:
          - url: http://babyblue:7860
        passHostHeader: true
    stable_diffusion2:
      loadBalancer:
        servers:
          - url: http://babyblue:7860
        passHostHeader: true
    tabbyml:
      loadBalancer:
        servers:
          - url: http://192.168.1.124:8080
        passHostHeader: true
    pihole:
      loadBalancer:
        servers:
          - url: http://192.168.1.3
        passHostHeader: true
    uptime_kuma_summary:
      loadBalancer:
        servers:
          - url: https://uptime-kuma.paynepride.com/
        passHostHeader: true
    littlelink:
      loadBalancer:
        servers:
          - url: https://pypeaday.github.io/littlelink/
        passHostHeader: true
    rickroll:
      loadBalancer:
        servers:
          - url: https://pypeaday.github.io/rick/
        passHostHeader: true
  # endregion
  middlewares:
    simple-auth:
      basicAuth:
        usersFile: /etc/traefik/usersFile
    test-apikey:
      plugin:
        apiKey:
          # mysecret
          secretParam: $apr1$Yvgg4UCA$TN9OKxz19sDeVhNQRJr7X/
    addprefix-pihole:
      addPrefix:
        prefix: /admin
    addprefix-uptime:
      addPrefix:
        prefix: /status/summary
    redirect-uptime:
      redirectRegex:
        regex: https://status.paynepride.com
        replacement: https://uptime_kuma.paynepride.com/status/summary
        permanent: true
    addprefix-transmission:
      addPrefix:
        prefix: /transmission/web/
    https-redirect:
      redirectScheme:
        scheme: https
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
    default-whitelist:
      ipWhiteList:
        sourceRange:
          - 10.220.108.0/24  # wg
          - 192.168.1.0/24  # lan
          - 172.17.0.0/16  # docker
          - 172.19.0.0/16  # docker
          - 172.20.0.0/16  # docker
          - 172.22.0.0/16  # docker
    extended-whitelist:
      ipWhiteList:
        sourceRange:
          - 10.220.108.0/24  # wg
          - 192.168.1.0/24  # lan
          - 172.17.0.0/16  # docker
          - 71.66.253.233/32  # block WAN
    secured:
      chain:
        middlewares:
          - default-whitelist
          - default-headers
